# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
   include:
     - master
  paths:
    include:
      - src/MessageApi/*
   
  
pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  projectFile: 'src/MessageApi/messageApi/*.csproj'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: $(projectFile)
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
   command: build
   projects: $(projectFile)
   configuration: $(buildConfiguration)
- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: false
    projects: $(projectFile)
    configuration: $(buildConfiguration)
    arguments: '--output $(build.artifactstagingdirectory)'
    zipAfterPublish: true
- task: PublishBuildArtifacts@1
  displayName: Publish Artefacts
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()   
